### ISSUE TITLE
Lollipop issue

### ISSUE THREAD

**Issue by DaRolla** [marvinlabs/android-slideshow-widget#23]
Hi marvinlabs :-)

When using com.android.support:appcompat-v7:21.0.3 my app crashes only on Nexus 5 with Android 5.0.1 inflating the SlideShowView:

Caused by: java.lang.ClassCastException: android.graphics.drawable.RippleDrawable cannot be cast to android.graphics.drawable.StateListDrawable
            at com.marvinlabs.widget.slideshow.SlideShowView.readAttributeSet(SlideShowView.java:159)
            at com.marvinlabs.widget.slideshow.SlideShowView.<init>(SlideShowView.java:144)
            at com.marvinlabs.widget.slideshow.SlideShowView.<init>(SlideShowView.java:138)

So taking a look at your code I can see that you use android.R.attr.selectableItemBackground as a fallback for onClickedDrawable (which is a StateListDrawable).

Here comes a tiny workaround:
Take a look at android-sdk\platforms\android-14\data\res\values at attrs.xml, styles.xml and themes.xml.The StateListDrawable is item_background_holo_light.xml referencing some drawables. So I copied them all, fixed, the references, an at least this is working.
Place this into the layout containg the SlideShowView:
  app:selector="@drawable/item_background_holo_light"

The item_background_holo_light.xml contains:
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_pressed="true" android:drawable="@drawable/list_pressed_holo_light"/>
    <item android:state_focused="false" android:drawable="@android:color/transparent"/>
    <item android:drawable="@android:color/transparent"/>
</selector>

The list_pressed_holo_light.png can be found in android-sdk\platforms\android-14\data\res\drawable-xhdpi and other densities.

Best regards,
DaRolla

**Comment by vpratfr** [comment]
Hi,

The best thing would be to get the ripple effect too. With your fix there would be none I guess? 

Feel free to fork and submit a pull request, I don't have time to work on the library currently but would be happy to include some patches.

**Comment by liloargana** [comment]
Line 73: Change the variable declaration to Drawable solved it for me.

private Drawable onClickedDrawable;

**Comment by garenacupson** [comment]
how to solve Error inflating class com.marvinlabs.widget.slideshow.SlideShowView?

**Comment by garenacupson** [comment]
java.lang.ClassCastException: android.graphics.drawable.RippleDrawable cannot be cast to android.graphics.drawable.StateListDrawable
	at com.marvinlabs.widget.slideshow.SlideShowView.readAttributeSet(SlideShowView.java:159)
	at com.marvinlabs.widget.slideshow.SlideShowView.<init>(SlideShowView.java:144)
	at com.marvinlabs.widget.slideshow.SlideShowView.<init>(SlideShowView.java:138)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:379)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:99)
	at com.android.tools.idea.rendering.LayoutlibCallback.loadView(LayoutlibCallback.java:172)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:207)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:132)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:806)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:385)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:400)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:332)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderService$5.compute(RenderService.java:688)
	at com.android.tools.idea.rendering.RenderService$5.compute(RenderService.java:677)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.android.tools.idea.rendering.RenderService.createRenderSession(RenderService.java:677)
	at com.android.tools.idea.rendering.RenderService.render(RenderService.java:815)
	at com.intellij.android.designer.designSurface.AndroidDesignerEditorPanel$6.run(AndroidDesignerEditorPanel.java:480)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:327)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cristidregan** [comment]
Is there a way to use this library on lollipop or not?
