### ISSUE TITLE
Inflation issue

### ISSUE THREAD

**Issue by maazasif** [marvinlabs/android-slideshow-widget#32]
Hi. 

I added the dependency for the library and everything synced fine. But as soon as i ran the application, i got an exception (just added the widget in xml and nothing in the code). The trace is as follows:

02-26 15:31:37.911 11421-11421/com.video.ccolutions.videoeditor W/System.err: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.marvinlabs.widget.slideshow.SlideShowView
02-26 15:31:37.918 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:561)
02-26 15:31:37.918 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:437)
02-26 15:31:37.918 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
02-26 15:31:37.918 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
02-26 15:31:37.918 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
02-26 15:31:37.918 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at com.video.ccolutions.videoeditor.SlideshowCreation.onCreate(SlideshowCreation.java:58)
02-26 15:31:37.918 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.app.Activity.performCreate(Activity.java:6372)
02-26 15:31:37.919 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
02-26 15:31:37.919 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
02-26 15:31:37.919 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
02-26 15:31:37.919 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:168)
02-26 15:31:37.919 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
02-26 15:31:37.919 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-26 15:31:37.919 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.os.Looper.loop(Looper.java:150)
02-26 15:31:37.919 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5659)
02-26 15:31:37.919 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-26 15:31:37.919 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
02-26 15:31:37.919 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
02-26 15:31:37.919 11421-11421/com.video.ccolutions.videoeditor W/System.err: Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.marvinlabs.widget.slideshow.SlideShowView
02-26 15:31:37.919 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:672)
02-26 15:31:37.920 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:791)
02-26 15:31:37.920 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:731)
02-26 15:31:37.920 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:862)
02-26 15:31:37.920 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825)
02-26 15:31:37.920 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
02-26 15:31:37.920 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825)
02-26 15:31:37.920 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
02-26 15:31:37.920 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:825)
02-26 15:31:37.920 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:537)
02-26 15:31:37.920 11421-11421/com.video.ccolutions.videoeditor W/System.err: 	... 17 more
02-26 15:31:37.920 11421-11421/com.video.ccolutions.videoeditor W/System.err: Caused by: java.lang.reflect.InvocationTargetException
02-26 15:31:37.920 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
02-26 15:31:37.920 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:641)
02-26 15:31:37.920 11421-11421/com.video.ccolutions.videoeditor W/System.err: 	... 26 more
02-26 15:31:37.920 11421-11421/com.video.ccolutions.videoeditor W/System.err: Caused by: java.lang.ClassCastException: android.graphics.drawable.RippleDrawable cannot be cast to android.graphics.drawable.StateListDrawable
02-26 15:31:37.921 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at com.marvinlabs.widget.slideshow.SlideShowView.readAttributeSet(SlideShowView.java:159)
02-26 15:31:37.921 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at com.marvinlabs.widget.slideshow.SlideShowView.<init>(SlideShowView.java:144)
02-26 15:31:37.921 11421-11421/com.video.ccolutions.videoeditor W/System.err:     at com.marvinlabs.widget.slideshow.SlideShowView.<init>(SlideShowView.java:138)
02-26 15:31:37.921 11421-11421/com.video.ccolutions.videoeditor W/System.err: 	... 28 more

I have no idea why this is happened so need all the help i can get.

Thanks.

**Comment by vpratfr** [comment]
Hi,

`java.lang.ClassCastException: android.graphics.drawable.RippleDrawable cannot be cast to android.graphics.drawable.StateListDrawable`

You may try the workaround from #23 

If you have a proper fix, do not hesitate to submit a PR, I will happily merge it.

**Comment by aliraza96** [comment]
This fix doesn't work anymore !!!!
